#!/usr/bin/env bash
# Run the whole stack locally: coordinator + cloud API + web console.
#
# The web console alone is not enough to see anything. Every page after
# sign-in calls the cloud API, and the cloud API refuses to start without a
# coordinator to front — so a lone `npm run dev` shows "Failed to fetch" on
# every screen, which looks like a bug and is not one.
#
#   ./scripts/dev.sh            # coordinator + API (web runs separately)
#   ./scripts/dev.sh --all      # the above plus `npm run dev`
#
# Ctrl-C stops everything.
#
# WHICH DATABASE (changed 2026-08-02). Defaults to `.env.dev`, which points at
# the flashml-dev Supabase project. Until this change there was only `.env`,
# and it pointed DATABASE_URL at the PRODUCTION pooler — so running this
# script read and wrote the same rows the deployed console serves. Local
# development was a second client of production, not a separate environment.
#
#   ./scripts/dev.sh --all                    # .env.dev  (default, safe)
#   ./scripts/dev.sh --all --env .env         # refused: that is production
#   ./scripts/dev.sh --all --env .env --i-mean-production
#
# BINDING (also 2026-08-02). Loopback by default. `--host 0.0.0.0` exposes the
# coordinator and API on your LAN so a SECOND MACHINE can join and actually
# exercise multi-machine collaboration — the one thing a loopback-only stack
# can never test, because nothing else can reach it.
#
#   ./scripts/dev.sh --all --host 0.0.0.0
#   # then on the other machine:
#   #   flashnode work --coordinator http://<this-machine-ip>:8000

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE="$ROOT/.local-state/dev"
API_VENV="$ROOT/flashml-cloud/apps/api/.venv"

COORDINATOR_PORT="${COORDINATOR_PORT:-8100}"
API_PORT="${API_PORT:-8000}"

if [[ ! -x "$API_VENV/bin/python" ]]; then
  echo "error: no venv at $API_VENV" >&2
  echo "  cd flashml-cloud/apps/api && uv venv .venv \\" >&2
  echo "    && uv pip install -e ../../../flashruntime -e '.[dev]'" >&2
  exit 1
fi

ENV_FILE="${FLASHML_ENV_FILE:-.env.dev}"
BIND_HOST="127.0.0.1"
ALLOW_PRODUCTION=0
ARGS=()
while (( $# )); do
  case "$1" in
    --env)  ENV_FILE="$2"; shift 2 ;;
    --host) BIND_HOST="$2"; shift 2 ;;
    --i-mean-production) ALLOW_PRODUCTION=1; shift ;;
    *) ARGS+=("$1"); shift ;;
  esac
done
set -- "${ARGS[@]+"${ARGS[@]}"}"

if [[ ! -f "$ROOT/$ENV_FILE" ]]; then
  echo "error: no $ENV_FILE at the repo root" >&2
  if [[ "$ENV_FILE" == ".env.dev" ]]; then
    echo "  cp .env.dev.example .env.dev  # then fill in DATABASE_PASSWORD" >&2
    echo "  (Supabase -> flashml-dev -> Settings -> Database)" >&2
  else
    echo "  copy .env.example and fill it in" >&2
  fi
  exit 1
fi

# SUPABASE_URL and DATABASE_URL come from a gitignored env file, so the real
# values live in exactly one place and never in this script.
set -a
# shellcheck disable=SC1091
source "$ROOT/$ENV_FILE"
set +a

# THE PRODUCTION GUARD.
#
# Matching on the project ref in DATABASE_URL rather than on the filename: the
# thing that decides which rows you mutate is the connection string, and
# somebody will eventually paste a prod URL into .env.dev. `yualksqjjvlfscbbsygq`
# is flashml-poc, the production project.
if [[ "${DATABASE_URL:-}" == *"yualksqjjvlfscbbsygq"* && "$ALLOW_PRODUCTION" != "1" ]]; then
  echo "refusing to start: $ENV_FILE points DATABASE_URL at PRODUCTION" >&2
  echo "  (project yualksqjjvlfscbbsygq / flashml-poc)" >&2
  echo "" >&2
  echo "  Use the dev database:   ./scripts/dev.sh --all --env .env.dev" >&2
  echo "  Or, if you truly mean it, add --i-mean-production" >&2
  exit 1
fi

if [[ "$BIND_HOST" != "127.0.0.1" ]]; then
  echo ">>> binding $BIND_HOST — reachable from other machines on this network." >&2
  echo ">>> env: $ENV_FILE" >&2
fi

mkdir -p "$STATE/artifacts"

# The coordinator's ledger and artifact defaults are /data/... — correct for
# the Render disk, unwritable on a laptop, and the resulting error
# ("Read-only file system: '/data'") names neither the setting nor the fix.
# Point both at repo-local state instead.
export FLASHML_LEDGER_PATH="$STATE/flashruntime.db"
export FLASHML_LOCAL_ARTIFACTS_DIR="$STATE/artifacts"
# KubeRay needs a cluster. There isn't one.
export FLASHML_ENABLE_KUBERAY=0

# Dev-only operator credential, regenerated every run so it cannot drift
# into a commit or outlive the process that used it. Production's is
# generated by Render (`generateValue` in render.yaml) and never seen by a
# human.
OPERATOR_TOKEN="dev-$(head -c 24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9')"
export FLASHML_OPERATOR_TOKENS="flashml-api:${OPERATOR_TOKEN}"
export FLASHML_REQUIRE_NODE_AUTH=1

export COORDINATOR_URL="http://127.0.0.1:${COORDINATOR_PORT}"
export COORDINATOR_OPERATOR_TOKEN="$OPERATOR_TOKEN"
export FLASHML_REQUIRE_AUTH=true
export FLASHML_CONSOLE_URL="http://localhost:3000"

pids=()
cleanup() {
  trap - INT TERM EXIT
  for pid in "${pids[@]:-}"; do
    kill "$pid" 2>/dev/null || true
  done
  wait 2>/dev/null || true
}
trap cleanup INT TERM EXIT

echo "coordinator  http://127.0.0.1:${COORDINATOR_PORT}   (private in production — do not expose)"
# `python -m uvicorn`, not the `uvicorn` console script. A venv's scripts
# hardcode an absolute shebang, so moving or renaming the checkout leaves
# every one of them pointing at a path that no longer exists — and the error,
# "bad interpreter: .../python3.14: No such file or directory", names an
# interpreter rather than the venv, which sends you looking for a Python
# version problem you do not have. Going through the interpreter directly
# cannot break that way. (Renaming the checkout is exactly what broke this.)
#
# --workers 1 is required, not a default: LeaseManager and SqliteLeaseStore
# are only safe on a single event loop (HANDOFF.md risk #5).
"$API_VENV/bin/python" -m uvicorn flashruntime.service.app:app \
  --host "$BIND_HOST" --port "$COORDINATOR_PORT" --workers 1 --log-level warning &
pids+=($!)

# Wait for it to answer rather than sleeping a guessed interval: the API
# checks its coordinator at startup, and a fixed sleep is the difference
# between "works on my machine" and a confusing boot failure on a cold cache.
for _ in $(seq 1 40); do
  if curl -fsS "http://127.0.0.1:${COORDINATOR_PORT}/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 0.25
done

echo "cloud API    http://127.0.0.1:${API_PORT}"
cd "$ROOT/flashml-cloud/apps/api"
"$API_VENV/bin/python" -m uvicorn flashml_cloud_api.app:app \
  --host "$BIND_HOST" --port "$API_PORT" --log-level info &
pids+=($!)

if [[ "${1:-}" == "--all" ]]; then
  echo "web console  http://localhost:3000"
  cd "$ROOT/flashml-cloud/apps/web"
  npm run dev &
  pids+=($!)
else
  echo
  echo "web console: run this in another terminal"
  echo "  cd flashml-cloud/apps/web && npm run dev"
fi

echo
echo "Ctrl-C to stop."
wait
