-- 0005_job_rounds_clipped.sql
--
-- Bounded influence: which of a round's contributions the aggregation
-- capped, and whose machine sent them.
--
-- WHY THIS EXISTS. `fedavg_weights.reduce_deltas` already refuses everything
-- MALFORMED -- non-positive or non-finite sample counts, NaN/Inf weights --
-- but a contribution can be perfectly well-formed and still adversarial:
-- delta = 1e6 with an honest n = 500 passes every guard, and the
-- sample-weighted mean then moves the shared model by whatever the sender
-- chose. One node out of a quorum could steer the result arbitrarily. The
-- runtime now clips any contribution whose L2 norm exceeds
-- median(norms) x 3.0 -- self-scaling, so an honest round, where no norm
-- exceeds the cap, is bit-identical to what it was before -- and reports
-- what it clipped. This column is where that report lands.
--
-- RECORDED, NEVER ENFORCED. Nothing here quarantines a machine, withholds a
-- credit or refuses a lease; the row exists so the operator can look and
-- revoke by hand. With a fleet this size a false positive costs a volunteer
-- their machine while a false negative costs one undeserved credit, and that
-- asymmetry only points one way. See
-- docs/superpowers/specs/2026-08-03-bounded-influence-design.md, decision 2.
--
-- SHAPE: an array of {task_id, norm, cap, scale, node_id} objects. The
-- runtime reports positional indices, the driver resolves them to task ids
-- (the only identity it holds), and the API's `on_round` adds `node_id` by
-- joining on the same accepted-task list that feeds the credit ledger -- so
-- provenance and credit can never name different machines for one task. A
-- task with no accepted node stores `node_id: null` rather than being
-- dropped: an attempt to steer the model that left no trace is worse than
-- one recorded against an unknown machine.
--
-- jsonb rather than a table of its own, matching `contributors` next to it:
-- it is read straight back out as JSON, it is never joined on or aggregated,
-- and the wire shape may grow richer per-contribution detail later.
--
-- `not null default '[]'` so every round has an answer to "what did the cap
-- bind?" -- on an honest round, which is every round unless somebody tried,
-- that answer is the empty list. A nullable column would make every reader
-- distinguish two kinds of nothing.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are two databases, dev (auto-migrated on
-- merge to `develop`) and production (gated behind a manual workflow).
-- Project refs deliberately not named here: they belong in the gitignored
-- env files and in Render's `sync: false` prompts, nowhere in git. The runner
-- is what keeps the two honest, so do not apply this by hand to either.
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.
--
-- Idempotent, and safe on a live table: adding a column with a non-volatile
-- default does not rewrite the heap on any supported PostgreSQL version.

alter table public.job_rounds
    add column if not exists clipped jsonb not null default '[]'::jsonb;

comment on column public.job_rounds.clipped is
    'Contributions whose influence this round''s aggregation capped, as '
    '{task_id, norm, cap, scale, node_id} objects; empty on an honest '
    'round. node_id is joined from the round''s accepted tasks and is null '
    'when no accepted task claims it. Recorded for the operator to inspect '
    'and act on by hand -- nothing is enforced from this column.';
