-- 0006_verifications.sql
--
-- The verification ledger: what the API believes about work it was told
-- happened, and what it refuses to claim it believes.
--
-- WHY THIS EXISTS. Every check the system runs today passes for a node that
-- did nothing at all: the output file exists, its hash matches (it hashed
-- what it uploaded), the values are finite, the shapes agree, the norm is
-- unremarkable. A lazy node that returns zeros earns a `contributions` row
-- identical to an honest node's. Bounded influence (0005) caps how far one
-- contributor can move a federated model; it detects no lie. This table is
-- where a detected one lands.
--
-- RECORDED, NEVER ENFORCED. Nothing reads this table to refuse a lease,
-- withhold a credit, fail a commit or change placement. Two reasons, and the
-- second is the strong one: (1) a false positive costs a volunteer their
-- machine while a false negative costs one undeserved credit, and with a
-- fleet of two that asymmetry is decisive; (2) a redundancy mismatch does
-- not identify the liar -- two results disagree and there is no trusted
-- third opinion, so auto-punishing punishes the honest node half the time.
-- See docs/superpowers/specs/2026-08-03-result-verification-design.md, §5.
--
-- `unknown` IS A FIRST-CLASS VERDICT and the reason the check constraint
-- lists three values rather than two. Too few peers, a peer distribution
-- that says nothing, an agent too old to report evidence -- all of them are
-- "we could not tell", and a schema offering only pass/flag would force
-- every one of them to be written as `pass`. Absence of evidence is not
-- evidence of honesty (§2.1, §8.8), and that is the error most likely to
-- creep in on any later reader too: count `verdict = 'pass'`, never
-- `verdict <> 'flag'`.
--
-- NO UNIQUE CONSTRAINT, deliberately. Three slices judge the same task
-- independently and each writes its own row; a `timing` pass and an
-- `evidence` flag about one task are two findings, not a conflict. Nor is
-- this idempotent by schema the way `contributions` is (0003): it does not
-- need to be, because the only writer runs behind
-- `db.claim_attempt_credit`, which hands out the right to record a lease
-- exactly once. A second writer added later must bring its own guard rather
-- than assume one here.
--
-- `machine_id` IS NULLABLE, unlike every other machine reference in this
-- schema. A redundancy mismatch is about a PAIR and names neither member as
-- the guilty one (§8.5). A row forced to blame one of the two would be a
-- fabricated accusation; `null` is the honest shape, and it is why this
-- column is not `not null` merely because every writer today happens to
-- supply it.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are two databases, dev (auto-migrated on
-- merge to `develop`) and production (gated behind a manual workflow).
-- Project refs deliberately not named here: they belong in the gitignored
-- env files and in Render's `sync: false` prompts, nowhere in git. The runner
-- is what keeps the two honest, so do not apply this by hand to either.
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

create table if not exists public.verifications (
    id          uuid primary key default gen_random_uuid(),
    -- Nullable on purpose -- see the header. `on delete cascade` so a
    -- revoked host's verdicts do not outlive the machine they describe.
    machine_id  uuid references public.machines(id) on delete cascade,
    -- Matches `contributions`: for a federated run this is the ROUND's
    -- coordinator job id, not the parent run, because that is the id the
    -- credit path holds and the two must be joinable.
    job_id      text not null,
    task_id     text not null,
    slice       text not null check (slice in ('timing','evidence','redundancy')),
    verdict     text not null check (verdict in ('pass','flag','unknown')),
    -- What the check actually saw, so a verdict can be argued with. Shape is
    -- the slice's business; `not null default '{}'` so every row answers the
    -- question rather than making readers distinguish two kinds of nothing.
    detail      jsonb not null default '{}'::jsonb,
    created_at  timestamptz not null default now()
);

comment on table public.verifications is
    'One slice''s verdict on one task: pass / flag / unknown, plus what it '
    'saw. ADVISORY ONLY -- nothing in this system reads this table to '
    'refuse a lease, withhold a credit or change placement. unknown means '
    '"could not tell" and is never the same as pass: count verdict = '
    '''pass'', never verdict <> ''flag''. machine_id is null when a finding '
    'is about a pair of machines rather than one of them.';

alter table public.verifications enable row level security;

-- Serves the cascade delete above and the "what have we ever said about
-- this host" query an operator runs before revoking anybody by hand.
create index if not exists verifications_machine_id_idx
    on public.verifications (machine_id);
-- Serves the per-job view: every verdict recorded against one job's tasks.
create index if not exists verifications_job_id_idx
    on public.verifications (job_id);
