-- 0007_pools.sql
--
-- Team pools: members, invites, and admission gate.
--
-- WHY THIS EXISTS. A pool is a team: members share machines and any member's
-- pool-scoped jobs run only on the team's workers. Pool membership is a many-
-- to-many relationship (a profile can belong to multiple pools; a pool has
-- multiple members). Every pool has an owner (the profile that created it).
--
-- Invites are one-time-use links (link-scoped, not account-scoped). Consuming
-- an invite both admits the account through the alpha signup gate (which gates
-- all new accounts against an allowlist of invoked addresses) and joins the
-- account to the pool.
--
-- A job can opt into pool scoping: null pool_id is every pre-pools job.
--
-- HOW THIS IS APPLIED (updated 2026-08-03): by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are now TWO databases, dev (auto-migrated
-- on merge to `develop`) and production (gated behind a manual workflow).
-- Project refs deliberately not named here: they belong in the gitignored
-- env files and in Render's `sync: false` prompts, nowhere in git. The runner
-- is what keeps the two honest, so do not apply this by hand to either.
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

create table if not exists public.pools (
    id         uuid primary key default gen_random_uuid(),
    name       text not null,
    owner_id   uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now()
);
comment on table public.pools is
    'A team: members pool all their machines and any member''s pool-scoped '
    'jobs run only on the team''s workers. Owned by the profile that created '
    'it; the owner is also a pool_members row.';
alter table public.pools enable row level security;
create index if not exists pools_owner_id_idx on public.pools (owner_id);

create table if not exists public.pool_members (
    pool_id   uuid not null references public.pools(id) on delete cascade,
    user_id   uuid not null references public.profiles(id) on delete cascade,
    joined_at timestamptz not null default now(),
    primary key (pool_id, user_id)
);
comment on table public.pool_members is
    'Membership. A machine''s pools are its OWNER''s memberships resolved at '
    'stamp time (machines.owner_id -> pool_members.user_id) — machines are '
    'never members directly.';
alter table public.pool_members enable row level security;
create index if not exists pool_members_user_id_idx on public.pool_members (user_id);

create table if not exists public.pool_invites (
    token_hash     text primary key,
    pool_id        uuid not null references public.pools(id) on delete cascade,
    created_by     uuid not null references public.profiles(id) on delete cascade,
    expires_at     timestamptz not null,
    uses_remaining integer not null,
    created_at     timestamptz not null default now()
);
comment on table public.pool_invites is
    'One invite link: sha256 of the raw token (raw returned exactly once, '
    'like machine tokens). Consuming an invite both ADMITS the account '
    'through the alpha signup gate and joins it to the pool.';
alter table public.pool_invites enable row level security;
create index if not exists pool_invites_pool_id_idx on public.pool_invites (pool_id);

-- A pool-scoped job remembers its pool; null is every pre-pools job.
alter table public.jobs add column if not exists
    pool_id uuid references public.pools(id);
create index if not exists jobs_pool_id_idx on public.jobs (pool_id);

-- The invite-only alpha gate. Everyone who existed before the gate is
-- grandfathered: locking out the owner's own accounts teaches nothing.
alter table public.profiles add column if not exists admitted_at timestamptz;
update public.profiles set admitted_at = now() where admitted_at is null;
