-- 0008_machine_pools.sql
--
-- Machine pool bindings and capability snapshot columns.
--
-- WHY THIS EXISTS. v1 inherited every machine from its owner; this migration
-- makes serving a pool an explicit per-machine choice, so on deploy existing
-- pools go quiet until machines are ticked in — intended. A binding NARROWS
-- membership, never grants it — the stamp intersects this table with
-- pool_members on the owner, so a binding to a pool the owner left is inert.
-- Capability columns are display-only snapshots from the latest registration
-- (register proxy, best-effort). Never read by placement or authorization.
--
-- HOW THIS IS APPLIED (updated 2026-08-03): by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are now TWO databases, dev (auto-migrated
-- on merge to `develop`) and production (gated behind a manual workflow).
-- Project refs deliberately not named here: they belong in the gitignored
-- env files and in Render's `sync: false` prompts, nowhere in git. The runner
-- is what keeps the two honest, so do not apply this by hand to either.
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

create table if not exists public.machine_pools (
    machine_id uuid not null references public.machines(id) on delete cascade,
    pool_id    uuid not null references public.pools(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (machine_id, pool_id)
);
comment on table public.machine_pools is
    'Per-machine opt-in: which of its owner''s pools this machine serves. '
    'A binding NARROWS membership, never grants it — the stamp intersects '
    'this table with pool_members on the owner, so a binding to a pool the '
    'owner left is inert.';
alter table public.machine_pools enable row level security;
create index if not exists machine_pools_pool_id_idx on public.machine_pools (pool_id);

-- Display-only capability snapshot from the latest registration (register
-- proxy, best-effort). Never read by placement or authorization.
alter table public.machines add column if not exists sandbox_capable boolean not null default false;
alter table public.machines add column if not exists argv_capable boolean not null default false;
alter table public.machines add column if not exists unsandboxed_argv_capable boolean not null default false;
alter table public.machines add column if not exists module_capable boolean not null default false;
