-- 0009_access_requests.sql
--
-- Onboarding profile fields, and the access-request queue that replaces the
-- invite gate.
--
-- WHY THIS EXISTS. `admitted_at` (0007) meant two things at once: allowed
-- into FlashML, and member of a pool — `pool_invites` says so outright.
-- Redeeming a workspace invite was therefore the only way in, and an
-- uninvited signup was a dead end with nothing to ask and nothing to
-- review. This separates them. Access is an account property an admin
-- decides here; pool membership stays a workspace property its owner
-- decides. `admitted_at` REMAINS the switch every gate reads — this table
-- is the paperwork behind it, not a replacement for it.
--
-- The backfill is load-bearing, not cosmetic: `access` is DERIVED (no row
-- => needs_onboarding), so without it every grandfathered tester would be
-- shown the onboarding form despite already being admitted.
--
-- auth.users is deliberately untouched. That schema is Supabase's; the
-- email address is read from it, never written.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are two databases, dev (auto-migrated on
-- merge to `develop`) and production (gated behind a manual workflow).
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later
-- migration.

-- ---------------------------------------------------------------------------
-- profiles: the facts a user owns and edits forever.
-- ---------------------------------------------------------------------------
alter table public.profiles add column if not exists first_name        text;
alter table public.profiles add column if not exists last_name         text;
alter table public.profiles add column if not exists company_name      text;
alter table public.profiles add column if not exists role              text;
alter table public.profiles add column if not exists team_size         text;
alter table public.profiles add column if not exists email_domain      text;
alter table public.profiles add column if not exists is_personal_email boolean;
alter table public.profiles add column if not exists is_admin          boolean not null default false;

comment on column public.profiles.email_domain is
    'Derived server-side from the auth.users address, never accepted from a '
    'client. Full host, so a subdomain stays distinguishable.';
comment on column public.profiles.is_admin is
    'Grants the access-request queue. Deliberately has no granting UI: set '
    'it with one UPDATE against your own row.';

create index if not exists profiles_email_domain_idx on public.profiles (email_domain);

-- ---------------------------------------------------------------------------
-- access_requests: one row per account, the point-in-time record that was
-- screened. `access` is derived from it and is never stored.
-- ---------------------------------------------------------------------------
create table if not exists public.access_requests (
    user_id         uuid primary key references public.profiles(id) on delete cascade,
    status          text not null check (status in ('pending', 'admitted', 'declined')),
    use_case        text,
    compute_sources text[] not null default '{}',
    heard_from      text,
    pending_pool_id uuid references public.pools(id) on delete set null,
    invited_by      uuid references public.profiles(id) on delete set null,
    requested_at    timestamptz not null default now(),
    decided_at      timestamptz,
    decided_by      uuid references public.profiles(id) on delete set null
);

comment on table public.access_requests is
    'One row per account. status drives the console''s access state (no row '
    '= needs_onboarding). pending_pool_id is a workspace invite redeemed '
    'before approval: the join is materialised when an admin approves.';

alter table public.access_requests enable row level security;
create index if not exists access_requests_status_idx
    on public.access_requests (status, requested_at);

-- ---------------------------------------------------------------------------
-- Backfill. Every account admitted before this migration keeps working and
-- is never shown the form. Accounts with a NULL admitted_at get no row on
-- purpose: they correctly compute as needs_onboarding.
-- ---------------------------------------------------------------------------
insert into public.access_requests (user_id, status, decided_at)
select p.id, 'admitted', p.admitted_at
  from public.profiles p
 where p.admitted_at is not null
on conflict (user_id) do nothing;
