-- 0014_sandbox_sessions.sql
--
-- The durable ledger for one Alibaba FC Agent Sandbox lifecycle: create,
-- prepare, hibernate, wake, evaluate, kill.
--
-- WHY THIS EXISTS. The sandbox lifecycle is a multi-minute conversation with
-- somebody else's cloud, and the interesting part of it happens while nothing
-- of ours is running: the sandbox sits deep-hibernated — its instance
-- destroyed, its filesystem snapshotted — for as long as training takes
-- elsewhere. Hard rule 3 says nodes are disposable and state is not, and this
-- is the sharpest case of it in the system: if the only record of "there is a
-- live sandbox `i-abc` in ap-southeast-1 that must be woken and then killed"
-- is a Python object in one API process, then a deploy, a crash or an OOM
-- during that wait leaks a sandbox that bills by the second and loses the run
-- with it. These two tables are what make "the API can die mid-hibernation and
-- recover" a true sentence rather than an intention.
--
-- TWO TABLES BECAUSE THEY ANSWER TWO DIFFERENT QUESTIONS. `sandbox_sessions`
-- is the CURRENT truth — one row, mutated by compare-and-set, which is what a
-- reconciler queries and what a controller races on. `sandbox_events` is the
-- HISTORY — append-only, gapless per session, which is what the evidence view
-- renders and what a judge reads. Collapsing them into one table would force
-- the reconciler to reduce the whole history on every sweep, and collapsing
-- them the other way would leave the demo with a state and no story.
--
-- NO TOKEN COLUMN, EVER. The sandbox authenticates to this system as an
-- ordinary machine: `public.machines` already holds a sha256 of its `fmk_`
-- token and hands the raw value out exactly once (0001), and the OSS
-- credentials it needs are presigned URLs minted per object and expiring on
-- their own (spec D5). Adding a token, a key, or a signed URL here would
-- recreate precisely the liability the GitHub App design removes: a table
-- whose leak grants somebody something. See `flashml-cloud/AGENTS.md`,
-- "Nothing stored is a credential". `error_message` is the one free-text
-- column and it is sanitized in the application before it is ever bound —
-- `sandbox_sessions.redact`, which is tested against presigned URLs, `fmk_`
-- tokens, `LTAI` access keys, bearer headers and PEM blocks.
--
-- RLS, AND WHAT "OWNER-SCOPED" MEANS HERE. Row Level Security is enabled on
-- both tables and DELIBERATELY has no policies at all, exactly as in 0001. In
-- Postgres, RLS with zero policies denies every role except the table owner
-- and BYPASSRLS (the `service_role` key this API uses), which is the whole
-- design: the database is API-only and the owner filter is folded into the
-- query itself, never applied afterwards in Python. `fetch_session_for_owner`
-- returns None both for a session that does not exist and for one belonging to
-- somebody else, and the route answers 404 to both — a 403 for "exists but not
-- yours" confirms to a guesser that the id is real. Same doctrine as
-- `fetch_pool_for_member` and `fetch_machine_for_owner`. Do not add a policy
-- naming `anon` or `authenticated` here; `test_no_migration_creates_any_policy_at_all`
-- forbids any policy at all, and that test is the doctrine.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are two databases, dev (auto-migrated on
-- merge to `develop`) and production (gated behind a manual workflow).
-- Project refs deliberately not named here: they belong in the gitignored env
-- files and in Render's `sync: false` prompts, nowhere in git.
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

-- ---------------------------------------------------------------------------
-- sandbox_sessions: one row per sandbox lifecycle, mutated by compare-and-set.
-- ---------------------------------------------------------------------------
create table if not exists public.sandbox_sessions (
    id                  uuid primary key default gen_random_uuid(),

    -- `public.profiles`, not `auth.users`, for two reasons. Every other table
    -- in this schema references profiles and none references auth.users —
    -- 0009 states outright that auth.users is Supabase's schema and is
    -- deliberately untouched — and profiles.id already references
    -- auth.users(id) on delete cascade (0001), so the guarantee is identical.
    -- The cascade is the second reason: a foreign key pointing INTO Supabase's
    -- schema with no action would make Supabase's own user-delete fail on our
    -- table, which is an outage in somebody else's product caused by ours.
    owner_id            uuid not null
                        references public.profiles(id) on delete cascade,

    -- The dedicated pool the sandbox machine serves (spec D3: exactly one
    -- machine in it, so no public task can claim the sandbox and no evaluation
    -- task can escape to another host). Cascades like every other child of
    -- `pools` — pool_members, machine_pools and pool_invites all do — so a
    -- deleted workspace does not leave this table as the one object that
    -- blocks the delete.
    pool_id             uuid not null
                        references public.pools(id) on delete cascade,

    -- NULL until the sandbox has been provisioned and enrolled. `set null`,
    -- not `cascade`: a session whose machine row was deleted still holds a
    -- live `external_sandbox_id` that must be woken and killed, and cascading
    -- would delete the only record that says so — turning a lost pointer into
    -- a leaked, billing sandbox nobody can find.
    machine_id          uuid references public.machines(id) on delete set null,

    -- Plain text with no foreign key, matching `attempts.job_id`,
    -- `contributions.job_id` and `verifications.job_id`. Those columns are
    -- text-without-FK on purpose: a job id here may name a row in
    -- `public.jobs` or a coordinator-side job, and a foreign key would refuse
    -- the second kind at exactly the moment there is nothing to be done
    -- about it.
    training_job_id     text not null,
    evaluation_job_id   text,

    provider            text not null default 'alibaba-fc-sandbox',
    region              text not null,
    template            text not null,

    -- The provider's id for the sandbox. UNIQUE because it is the recovery
    -- key: `unfinished_sessions` hands it to a reconciler, and two sessions
    -- claiming one sandbox would have them fight over whether to wake it or
    -- kill it. NULL until `create` has been observed to succeed — and the gap
    -- between "we asked for a sandbox" and "we know its id" is exactly the
    -- window `REQUESTED` exists to name.
    external_sandbox_id text unique,

    -- Constrained in the database so an invalid state cannot be written even
    -- by a bug in the API, same discipline as `machines.status` (0001). The
    -- legal TRANSITIONS between these are policy and live in
    -- `sandbox_sessions.py` as pure functions, because a state machine
    -- expressed in a trigger cannot be read, argued with, or tested without a
    -- database.
    state               text not null
                        check (state in ('REQUESTED', 'ACTIVE', 'PREPARED',
                                         'HIBERNATED', 'RESUMING', 'EVALUATING',
                                         'SUCCEEDED', 'FAILED', 'TERMINATED')),

    -- sha256 of the marker file written into the sandbox before hibernation
    -- and re-read after the wake. It is the evidence for the only continuity
    -- claim this design is allowed to make: the ENVIRONMENT survived. The
    -- process did not — deep hibernation destroys the instance — and no
    -- column here should ever be read as saying otherwise (spec D2).
    marker_sha256       text,

    -- The capability that powers the PUBLIC, no-auth evidence view. Nullable
    -- so a session's share view can be withdrawn by setting it to NULL, and
    -- UNIQUE so one token names one session. Generated by the APPLICATION
    -- (`sandbox_sessions.new_share_token`, 256 bits from `secrets`), never
    -- here: `gen_random_uuid()` as a default would make the one unauthenticated
    -- surface in this system guessable from a timestamp and a MAC address on
    -- any deployment whose uuid generation is not what we assume.
    share_token         text unique,

    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    terminated_at       timestamptz,

    -- Sanitized before it is bound, never raw. See the header.
    error_code          text,
    error_message       text
);

comment on table public.sandbox_sessions is
    'One Alibaba FC Agent Sandbox lifecycle. The CURRENT truth about a '
    'session, mutated only by compare-and-set from a known previous state so '
    'two controllers cannot both move one session — the append-only history '
    'is public.sandbox_events. Holds no credential of any kind: the sandbox '
    'authenticates as an ordinary machine (hashed token in public.machines) '
    'and reaches OSS through presigned URLs that are never stored.';

comment on column public.sandbox_sessions.external_sandbox_id is
    'The provider''s sandbox id, and the recovery key: a session that holds '
    'one and is not TERMINATED owns a sandbox that is still billing, whatever '
    'this API process happens to remember. UNIQUE so two sessions can never '
    'fight over one sandbox.';

comment on column public.sandbox_sessions.state is
    'Observed, never intended. A transition is written after the provider has '
    'been seen to be in the new state — so a call that succeeded remotely and '
    'failed in transit is reconciled by inspecting and then recording, not by '
    'assuming. Legal transitions are pure policy in sandbox_sessions.py.';

comment on column public.sandbox_sessions.marker_sha256 is
    'sha256 of the marker file, re-read after the wake. Evidence for '
    'ENVIRONMENT continuity across deep hibernation and nothing more: the '
    'instance is destroyed and the worker process does not survive, so no '
    'reader may take this as saying a process slept through it.';

comment on column public.sandbox_sessions.share_token is
    'Bearer capability for the public, unauthenticated evidence view. '
    'Generated by the application from `secrets`, never by a SQL default — '
    'this is the only surface in the system that answers without a JWT, and '
    'it must be unguessable rather than merely unique.';

comment on column public.sandbox_sessions.error_message is
    'SANITIZED ONLY. Passed through sandbox_sessions.redact before binding, '
    'which strips presigned-URL signatures, fmk_/fmu_ tokens, LTAI access '
    'keys, bearer headers, JWTs and PEM blocks. A provider SDK''s exception '
    'text routinely echoes the request that caused it.';

alter table public.sandbox_sessions enable row level security;

-- The reconciler's query, and the reason this table exists: every session
-- that owns a live sandbox and has not been terminated. PARTIAL, because the
-- answer is almost always the empty set on a table that only grows — an
-- unpartitioned index would be read in full to find nothing.
--
-- The predicate hardcodes 'TERMINATED' where the Python constant
-- TERMINAL_STATES says the same thing, and those two CAN drift. They are
-- pinned together by
-- test_sandbox_sessions.py::test_the_cleanup_index_predicate_matches_the_policy,
-- which is the only thing standing between a widened terminal set and a
-- reconciler that silently stops sweeping.
create index if not exists sandbox_sessions_unfinished_idx
    on public.sandbox_sessions (created_at)
 where external_sandbox_id is not null
   and state <> 'TERMINATED';

-- "Which sessions belong to this training job" — the submit route's
-- duplicate check and the job page's lookup.
create index if not exists sandbox_sessions_training_job_idx
    on public.sandbox_sessions (training_job_id);

-- Owner-scoped listing, newest first, matching machines_owner_id_idx /
-- jobs_owner_id_idx / cli_credentials_owner_idx. Every owner-scoped read in
-- this schema has one; a session list that sequential-scans is the same bug
-- those indexes exist to prevent.
create index if not exists sandbox_sessions_owner_idx
    on public.sandbox_sessions (owner_id, created_at desc);

-- ---------------------------------------------------------------------------
-- sandbox_events: APPEND ONLY. Nothing updates or deletes a row here.
-- ---------------------------------------------------------------------------
create table if not exists public.sandbox_events (
    id          bigserial primary key,
    session_id  uuid not null
                references public.sandbox_sessions(id) on delete cascade,

    -- Gapless from 1 per session, allocated server-side under the session
    -- row's lock. A client-chosen sequence would let a retry write a second
    -- row for one observation; a bare timestamp ordering would tie on the
    -- sub-millisecond pairs this lifecycle produces (pause is observed and
    -- recorded in the same breath) and render the story out of order.
    sequence    bigint not null check (sequence > 0),

    type        text not null,

    -- WHO SAW IT, which is the difference between evidence and assertion.
    -- 'fc' is the provider's own answer, 'runtime' is the coordinator or the
    -- agent, 'controller' is this API's observation of its own actions. A
    -- reader tracing a disputed latency needs to know which of the three is
    -- speaking; constrained so a fourth cannot appear without this list
    -- being reconsidered.
    source      text not null check (source in ('controller', 'fc', 'runtime')),

    observed_at timestamptz not null default now(),

    -- Measured, not derived. NULL when nothing was timed — an absent
    -- measurement must not read as an instantaneous one, which is what a
    -- `not null default 0` would say about every event that never held a
    -- stopwatch.
    latency_ms  double precision,

    -- `not null default '{}'` so every event answers "what else did you see?"
    -- rather than making readers distinguish two kinds of nothing, matching
    -- verifications.detail and job_rounds.clipped. Sanitized on the way in by
    -- the same redaction the error columns use.
    data        jsonb not null default '{}'::jsonb,

    -- Idempotency as a property of the TABLE, not of the caller's discipline
    -- — the same argument 0003 makes for the credit ledger. A controller that
    -- retries an append after a failed round trip must produce one row, and
    -- with this constraint it can insert with `on conflict do nothing` and be
    -- correct under retry.
    unique (session_id, sequence)
);

comment on table public.sandbox_events is
    'Append-only history of one sandbox session: what was OBSERVED, when, by '
    'whom, and how long it took. Nothing updates or deletes a row here. This '
    'is the P1 evidence for the lifecycle claims — the demo''s wake latency '
    'is read out of this table, not asserted in a slide.';

comment on column public.sandbox_events.sequence is
    'Gapless from 1 per session, allocated server-side under the session '
    'row''s lock. Unique with session_id, which is what makes a retried '
    'append one row instead of two.';

comment on column public.sandbox_events.source is
    'Who observed it: ''fc'' the provider, ''runtime'' the coordinator or '
    'agent, ''controller'' this API. Recorded because a latency the provider '
    'reports and one we timed around the provider are different claims.';

alter table public.sandbox_events enable row level security;

-- NO INDEX ON (session_id, sequence), deliberately — the `unique (session_id,
-- sequence)` constraint above is already backed by exactly that btree, and it
-- serves both the per-session read and its ordering. Adding a second would
-- double the write cost of an append-only table to buy nothing, which is the
-- same call 0010 and 0011 made and wrote down. Pinned by
-- test_sandbox_sessions.py::test_events_are_indexed_by_session_and_sequence,
-- which asserts the INDEX exists rather than how it got there.
--
-- Events are never queried by anything but their session, so there is no
-- second index here at all.
