-- 0022_rented_capacity.sql
--
-- One row per machine this control plane rented. The row is opened BEFORE
-- the venue is asked for anything, so a crash between "we decided to spend
-- money" and "the venue answered" leaves evidence rather than an orphan
-- that bills forever.
--
-- REQUESTED -> ACTIVE -> RELEASED, or -> FAILED from anywhere.
-- `provider_handle` is null only in REQUESTED; the reconciler's job is to
-- make that window short.
--
-- RLS. Row Level Security is enabled with DELIBERATELY no policies, exactly
-- as in 0001, 0007, 0014, 0018 and 0019. In Postgres, RLS with zero policies
-- denies every role except the table owner and BYPASSRLS (the `service_role`
-- key this API uses), which is the whole design: the database is API-only and
-- the owner filter is folded into the query itself. It is not decoration
-- here in particular — this table carries `owner_id`, `usd_per_hour` and
-- `provider_handle` together, so a table in `public` with RLS off is one
-- browser-shipped `anon` key away from being every tenant's rented-GPU bill,
-- readable AND writable. Do not add a policy naming `anon` or
-- `authenticated`; `test_schema.py::test_no_migration_creates_any_policy_at_all`
-- forbids any policy at all, and that test is the doctrine.
--
-- FOREIGN KEYS, AND THE ONE COLUMN THAT DELIBERATELY HAS NONE.
--
-- `owner_id` and `pool_id` cascade, like every other child of `profiles` and
-- `pools` in this schema (0007, 0014, 0018). The reason is not convenience
-- and 0018 states it at length: `profiles.id` references `auth.users(id) on
-- delete cascade`, so a `restrict` anywhere down this chain would make
-- SUPABASE'S OWN user delete fail on our table. The honest consequence is
-- written down rather than hidden, and it is worse here than it is for the
-- credit ledger: deleting an account deletes the record of money spent on its
-- behalf. Any claim of the form "we rented $N of capacity" is therefore a
-- statement about LIVE accounts and live pools, not about all spend ever. If
-- that record must outlive the account, it needs its own account-independent
-- ledger (an append-only spend journal keyed by nothing that cascades) —
-- which is a separate decision, not something to smuggle in by writing
-- `restrict` here and breaking somebody else's product.
--
-- `machine_id` is `set null`, not `cascade`, for exactly the reason 0014
-- gives for `sandbox_sessions.machine_id`: a row whose machine was deleted
-- still holds a live `provider_handle` that must be destroyed at the venue,
-- and cascading would delete the only record that says so — turning a lost
-- pointer into a leaked machine that bills forever and nobody can find.
--
-- `job_id` is text with NO foreign key, matching `attempts.job_id`,
-- `contributions.job_id`, `verifications.job_id`, `bids.job_id` and
-- `sandbox_sessions.training_job_id`. Those columns are text-without-FK on
-- purpose: a job id here may name a row in `public.jobs` OR a coordinator-side
-- job, and a foreign key would refuse the second kind at exactly the moment
-- there is nothing to be done about it — with a machine already rented and
-- billing. The types do match (`jobs.id` is `text`); this is a design
-- decision, not a type accident.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations against dev and, behind a manual gate, production.
--
-- Idempotent: safe to re-run (`create table if not exists`, `create index if
-- not exists`, re-runnable `alter table ... enable row level security` and
-- `comment on ...`).
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

create table if not exists public.rented_capacity (
    id                uuid primary key default gen_random_uuid(),
    venue_id          text        not null,
    state             text        not null default 'REQUESTED',

    owner_id          uuid        not null
                      references public.profiles(id) on delete cascade,
    pool_id           uuid        not null
                      references public.pools(id) on delete cascade,

    -- Text, no FK. See the header: a coordinator-side job id is a legitimate
    -- value here and an FK would refuse it mid-rental.
    job_id            text        not null,

    provider_handle   text,

    -- `set null`: losing the machine row must not lose the handle that says
    -- something is still billing.
    machine_id        uuid        references public.machines(id)
                      on delete set null,

    gpu_count         integer     not null default 1,
    usd_per_hour      numeric(10, 4),
    created_at        timestamptz not null default now(),
    acquired_at       timestamptz,
    released_at       timestamptz,
    failure_code      text,
    failure_detail    text,
    constraint rented_capacity_state_check
        check (state in ('REQUESTED', 'ACTIVE', 'RELEASED', 'FAILED'))
);

comment on table public.rented_capacity is
    'One row per machine this control plane rented, opened BEFORE the venue '
    'is asked for anything so that a crash between deciding to spend and '
    'hearing back leaves evidence rather than a machine that bills forever. '
    'REQUESTED -> ACTIVE -> RELEASED, or -> FAILED from anywhere. This is '
    'the table the budget ceilings are computed from, so a row that is not '
    'written is money that is not counted.';

comment on column public.rented_capacity.provider_handle is
    'The venue''s id for the machine — how we destroy it. Null only in '
    'REQUESTED, which is the window the reconciler exists to close: without '
    'this we are billing for something we cannot name.';

comment on column public.rented_capacity.usd_per_hour is
    'Quoted hourly rate. Null means the venue quoted no price, which '
    'capacity/budget.py refuses rather than treats as free — an unpriced '
    'acquisition cannot be bounded.';

comment on column public.rented_capacity.job_id is
    'Text with no foreign key, matching attempts.job_id, contributions.job_id, '
    'verifications.job_id, bids.job_id and sandbox_sessions.training_job_id: '
    'an id here may name a row in public.jobs or a coordinator-side job, and '
    'an FK would refuse the second kind with a machine already billing.';

alter table public.rented_capacity enable row level security;

-- The reconciler's query: everything still costing money.
create index if not exists rented_capacity_unreleased_idx
    on public.rented_capacity (state)
 where state in ('REQUESTED', 'ACTIVE');

create index if not exists rented_capacity_owner_idx
    on public.rented_capacity (owner_id, created_at desc);

create index if not exists rented_capacity_pool_idx
    on public.rented_capacity (pool_id, created_at desc);
