-- 0023_leased_machines.sql
--
-- A THIRD LIFECYCLE, BECAUSE A RENTAL'S IDENTITY IS A LEASE AND NOT A DEED.
--
-- 0020 split machine identities in two: `persistent` (a volunteer's laptop —
-- it keeps its identity until its owner revokes it) and `ephemeral` (a rental
-- session enrolled through the device-code flow — revoked after a heartbeat
-- grace period). A machine the CONTROL PLANE rents on a user's behalf is
-- neither, and until now it was filed as `persistent`, which is a lie about
-- hardware we hand back to a third party within the hour.
--
--   A laptop's binding is a DEED: it says whose machine this is, permanently.
--   A rental's binding is a LEASE: it is true while we hold the hardware and
--   false the moment we give it back.
--
-- `leased` says exactly that, and the row is the only place it can be said —
-- nothing else in `public.machines` distinguishes a rented pod from the
-- owner's laptop, so before this every rental left a permanent-looking entry
-- in its owner's fleet with a live token on hardware somebody else now has.
-- (Design: docs/superpowers/specs/2026-08-12-on-demand-capacity-design.md, D6.)
--
-- WHY NOT REUSE `ephemeral`, WHICH ALREADY MEANS "TEMPORARY".
--
-- `db.expire_stale_ephemeral_machines` selects `lifecycle = 'ephemeral'` and
-- measures from `coalesce(last_seen_at, created_at)` on a 15-minute default. A
-- rented host has NO `last_seen_at` until it has booted, pulled a
-- multi-gigabyte image and enrolled, which routinely takes longer than that —
-- so filing rentals as `ephemeral` would revoke the credentials of machines
-- that are still starting up, after we have already paid for the boot. That
-- sweep is deliberately left selecting `ephemeral` alone, and `leased` is
-- therefore outside every heartbeat timer in this schema.
--
-- The lease is instead ENDED BY THE RENTAL'S OWN LIFECYCLE: the
-- `public.rented_capacity` row and its release path. `capacity/reconcile.py`
-- revokes the credential on every path a rental ends, independently of the
-- destroy, and `finished_rentals_with_live_credentials` retries that revoke
-- for ever against rentals that are already over. A leased identity that
-- outlives its rental is a bug in that sweep, not a missing timer here.
--
-- `public.device_codes.lifecycle` IS DELIBERATELY UNCHANGED, still
-- `('persistent', 'ephemeral')`. That column carries a value an *agent* asks
-- for during enrolment, and `app.py` validates the request body against the
-- same two. A leased identity is minted by the control plane on its own
-- authority (`sandbox_identity.provision_rented_machine`) and never requested
-- by the host that will use it; letting an agent name `leased` for itself
-- would let it opt out of the fleet listing its owner reads.
--
-- No new table, no new column, no policy: this is a CHECK constraint widened
-- in place, so RLS on `public.machines` is exactly as 0001 left it — enabled,
-- with no policies at all.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are TWO databases, dev (auto-migrated on
-- merge to `develop`) and production (gated behind a manual workflow).
--
-- Idempotent: safe to re-run (`drop constraint if exists` + `add constraint`,
-- re-runnable `comment on`).
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

alter table public.machines
    drop constraint if exists machines_lifecycle_check;
alter table public.machines
    add constraint machines_lifecycle_check
        check (lifecycle in ('persistent', 'ephemeral', 'leased'));

comment on column public.machines.lifecycle is
    'persistent hosts keep their identity until owner revocation; ephemeral '
    'rental sessions are revoked after their heartbeat grace period; leased '
    'machines are rented by the control plane and their identity ends with '
    'the public.rented_capacity row that paid for them — never on a heartbeat '
    'timer, because a rented host has no heartbeat until it has finished '
    'pulling its image.';
