-- 0025_job_share_token.sql
--
-- A job gets the same bearer capability a sandbox session already has: one
-- unguessable token that opens ONE public, unauthenticated evidence page.
--
-- WHY THIS EXISTS. The submission needs a live URL that opens without a
-- login, and every console route redirects to sign-in. 0014 solved that for
-- a sandbox session and the mechanism has been in production since; the gap
-- is that the token is scoped to a *session*, so the FC hibernation story is
-- publicly viewable and the FAULT-TOLERANCE story — a machine dying and the
-- work resuming elsewhere, which is the product's actual claim — is not.
-- This column is that gap and nothing more. See
-- `docs/superpowers/specs/2026-08-12-agent-surface-decisions.md`, AS-7.
--
-- NULLABLE, AND NOT BACKFILLED. 0014 mints a session's token at create time
-- because a session exists to be evidence. A job does not: the overwhelming
-- majority of jobs are somebody's private training run and must stay that
-- way, so the column is NULL until a human asks for a link
-- (`POST /v1alpha1/jobs/{job_id}/share`). Minting is EXPLICIT, and a default
-- here — or an UPDATE backfilling the existing rows — would publish every
-- job this deployment has ever run in one migration.
--
-- NULL IS ALSO THE REVOCATION. Setting the column back to NULL kills the
-- link with no migration and no second state column, exactly as
-- 0014 designed it for sessions. A `revoked_at` column would have to be
-- consulted by every reader, and a reader that forgot would serve a revoked
-- page; there is nothing to forget when the token is simply gone.
--
-- UNIQUE, AND GENERATED BY THE APPLICATION. `job_share.new_share_token` is
-- `sandbox_sessions.new_share_token` — literally the same function, imported
-- rather than copied, so both kinds of token have one format (`shr_` +
-- 256 bits from `secrets`) and one entropy source. 0014 argues the rest and
-- it applies here word for word: a `gen_random_uuid()` DEFAULT would make the
-- only unauthenticated surface in this product guessable from a clock on any
-- deployment whose uuid generation is not what we assume.
--
-- ONE TOKEN SPACE, TWO KINDS OF THING, AND THAT IS DELIBERATE. `/share/<tok>`
-- resolves to either a session or a job. Uniqueness within each table plus 288
-- bits of entropy is what makes a collision across the two not worth
-- modelling; the resolver answers identically for "no such token", "the other
-- kind" and "revoked" so a prober cannot learn which table it missed
-- (AS-16, second point — the doctrine `redeem_device_code` already runs).
--
-- A PARTIAL UNIQUE INDEX, not an inline `unique` and not a full one. 0014
-- could write `share_token text unique` because it was creating the table;
-- an ALTER cannot say that idempotently, and `add constraint` is not
-- `if not exists`-able on this Postgres. A UNIQUE INDEX is, and making it
-- PARTIAL is the same call 0014 made for `sandbox_sessions_unfinished_idx`:
-- shared jobs are a rounding error against every job ever submitted, and an
-- unpartitioned index would carry one entry per NULL to buy nothing.
-- Uniqueness of the non-NULL tokens — the only uniqueness that means anything
-- here — is fully enforced by it.
--
-- NOT A CREDENTIAL FOR ANYTHING ELSE, and this bears repeating because a job
-- reaches further than a session does. The token opens a payload narrowed IN
-- SQL by `job_share.JOB_SHARE_COLUMNS`; it grants no read of `jobs.spec`,
-- `jobs.source`, the owner, the pool, artifacts, or the coordinator. The
-- authorship rule behind that narrowing is AS-16: *a session's output is
-- ours; a job's output is theirs*, because we execute user-supplied code from
-- a submitted repository and it prints whatever it prints.
--
-- Row Level Security on `public.jobs` is unchanged and still has no policies,
-- exactly as 0001 left it — which in Postgres denies every role except the
-- table owner and BYPASSRLS, and the owner filter stays folded into the
-- queries themselves. A column grants no access, and
-- `test_no_migration_creates_any_policy_at_all` is the doctrine.
--
-- Idempotent: `add column if not exists` + `create unique index if not
-- exists`, safe to re-run.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, in filename order, one transaction
-- per file. There are TWO databases, dev (auto-migrated on merge to
-- `develop`) and production (gated behind a manual workflow). Do not apply it
-- by hand to either.
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

alter table public.jobs
    add column if not exists share_token text;

comment on column public.jobs.share_token is
    'Bearer capability for the public, unauthenticated run page, or NULL. '
    'NULL is both the default (a job is private until somebody asks for a '
    'link) and the revocation (setting it back to NULL kills the link with '
    'no migration). Generated by the application from `secrets` — the same '
    'shr_ minter sandbox_sessions uses — and never by a SQL default: this is '
    'one of the two surfaces in the system that answer without a JWT, so it '
    'must be unguessable rather than merely unique. What the token opens is '
    'narrowed in SQL by job_share.JOB_SHARE_COLUMNS, never by a filter in a '
    'handler.';

create unique index if not exists jobs_share_token_key
    on public.jobs (share_token)
 where share_token is not null;
