-- 0028_machine_deletion.sql
--
-- A FOURTH MACHINE STATUS, BECAUSE THE ROW CANNOT BE DELETED AND THE DETAIL
-- MUST STILL GO.
--
-- Revoked machines accumulate in "My machines" for ever, each one a full
-- detail row — hostname, platform, capability snapshot, token prefix, last
-- heartbeat. The owner's complaint is that detail, and until now the only
-- exits from `public.machines` were `revoked` (which keeps every column) and
-- `DELETE` (which cannot be used at all).
--
-- WHY `DELETE` CANNOT BE USED. Six tables reference `public.machines(id)`
-- **on delete cascade**:
--
--   public.contributions  (0001) — the ACCEPTED-work credit ledger
--   public.attempts       (0004) — the attempt/lease evidence trail
--   public.verifications  (0006) — verdicts about work this machine did
--   public.machine_pools  (0008) — workspace bindings
--   public.listings       (0018) — asks, which price_observations cite
--   public.matches        (0018) — priced entitlements the ledger settles
--
-- Removing the row therefore erases the history that workspace hard rules 3
-- and 4 exist to protect: a person's accepted-task total would FALL when they
-- tidied their fleet, and a settled match would lose the machine it was
-- settled over. `db.contributions_for_owner` already anticipated exactly this
-- ("If one is ever added, note that contributions.machine_id cascades") and it
-- is why revoke stayed the only exit for as long as it did.
--
-- `deleted` is that exit: a TERMINAL TOMBSTONE. The row survives — every
-- foreign key above still resolves, every count still counts — and everything
-- that described the DEVICE is scrubbed by the same UPDATE that sets the
-- status (`db.delete_machine_row`): name, platform, capabilities,
-- token_hash, token_prefix, last_seen_at and the four capability booleans.
-- What is left is an id, an owner, a node_id and two timestamps: enough to
-- carry the history, not enough to describe a machine.
--
-- `node_id` STAYS, deliberately. It is `fn-<16 hex>` from the agent's own
-- state directory — an opaque identifier, not device detail — and it is the
-- key `enrolment.approve_device_code` matches on when the same machine
-- enrols again. Scrubbing it would make re-enrolment insert a SECOND row and
-- split one machine's history in two, which is the very thing the reactivate
-- branch was written to prevent.
--
-- WHY A STATUS AND NOT A `deleted_at IS NOT NULL` FLAG ALONE. `status` is
-- what every existing predicate in this schema already reads, and it is
-- CHECK-constrained, so a bug cannot write a state the API has never heard
-- of. A soft-delete flag beside an unchanged status would leave a row that
-- reads `revoked` to every query that has not been taught about the flag —
-- which is how a deleted machine comes back into a fleet listing.
-- `deleted_at` rides alongside for the same reason `revoked_at` does: it
-- records WHEN, and the row is the whole audit trail there is for machine
-- lifecycle (there is no machine event table; revoke records itself exactly
-- this way).
--
-- No new table, no policy: this is a CHECK constraint widened in place plus
-- one nullable column, so RLS on `public.machines` is exactly as 0001 left it
-- — enabled, with no policies at all. Migration 0023 widened
-- `machines_lifecycle_check` the same way.
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are TWO databases, dev (auto-migrated on
-- merge to `develop`) and production (gated behind a manual workflow).
--
-- Idempotent: safe to re-run (`drop constraint if exists` + `add constraint`,
-- `add column if not exists`, re-runnable `comment on`).
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

alter table public.machines
    drop constraint if exists machines_status_check;
alter table public.machines
    add constraint machines_status_check
        check (status in ('pending', 'active', 'revoked', 'deleted'));

alter table public.machines
    add column if not exists deleted_at timestamptz;

comment on column public.machines.status is
    'pending until a token is redeemed, active while that token works, '
    'revoked once it is killed, and deleted once the owner has retired the '
    'machine for good. deleted is TERMINAL and reached only from revoked: '
    'the row stays so the six tables that reference it keep resolving, but '
    'every column describing the device is cleared. Re-enrolling the same '
    'node_id revives the row rather than inserting a second one.';

comment on column public.machines.deleted_at is
    'When the owner deleted this machine, or null. Set by the same UPDATE '
    'that writes status = deleted and deliberately NOT cleared by '
    're-enrolment, exactly as revoked_at is not: it records that a deletion '
    'happened, which stays true afterwards.';
