-- 0030_official_providers.sql
--
-- THE MACHINES WE RUN OURSELVES SAY SO. One boolean on public.machines.
--
-- WHY THIS EXISTS. Every row on the network page is anonymised to everyone but
-- its owner: `prov…` plus six characters of the node id (see `network._label`
-- and its module docstring). That rule is right for a volunteer's laptop and
-- for a host's rented GPU — a machine's `name` is routinely a person's own
-- name — and it is exactly wrong for the anchor capacity Zolli Labs operates
-- itself. A network whose every provider is an unidentifiable handle gives a
-- buyer nothing to start from; the platform's own machines are the one part of
-- the fleet that has an accountable operator, a published identity, and a
-- reason to be recognised.
--
-- So `official = true` means: THIS MACHINE IS PLATFORM-OPERATED ANCHOR
-- CAPACITY, AND ITS NAME IS PUBLIC. Both halves are the same decision. The
-- flag is not a quality score, not a trust tier, and not a routing input —
-- `machines.sandbox_capable` / `argv_capable` / `unsandboxed_argv_capable`
-- already carry the practical trust tier (`network._badge`), the marketplace
-- already prices on measured acceptance, and adding a fourth thing that looks
-- like a ranking signal is how "official" quietly becomes "preferred" without
-- anyone deciding it should be.
--
-- WHY A COLUMN AND NOT A NAME CONVENTION. The obvious cheaper version is "any
-- machine whose owner is the Zolli Labs account shows its name". It is wrong
-- twice: it makes an identity decision out of a row that can be re-owned or
-- re-parented, and it silently de-anonymises every machine that account ever
-- enrols, including the ones enrolled to test something. The flag is EXPLICIT
-- and per-machine because publishing a name is a disclosure, and a disclosure
-- should be a thing somebody turned on for one machine rather than a side
-- effect of who happens to own it.
--
-- DEFAULT FALSE, NOT NULL. There is no third state. NULL would mean "nobody
-- has said", and every reader would then have to decide whether an unsaid
-- machine is anonymous — a question with exactly one safe answer, which is
-- better written as the default than re-derived at each call site. Every
-- machine enrolled before this migration is `false`, which is the behaviour
-- they have today.
--
-- WHO MAY SET IT. `network.set_machine_official`, and only for a machine the
-- caller OWNS and that is `active` — the ownership predicate lives in the
-- WHERE clause, exactly as `set_machine_location` does it. This is deliberately
-- an owner-set flag rather than an admin-set one: the platform's anchor
-- machines are enrolled by the platform's own account, so ownership is already
-- the fact being asserted, and a separate admin surface would be a second
-- authorisation path over the same row. If this ever needs to mean "vetted by
-- Zolli Labs" for machines Zolli Labs does NOT own, that is a different column
-- with a different audit story — do not repurpose this one.
--
-- NO INDEX, deliberately. The only read is the fleet-wide provider list, which
-- already scans `machines where status = 'active'` and returns every row; a
-- boolean with an overwhelmingly dominant value is also the worst possible
-- btree. Add one if and when something filters on it.
--
-- Idempotent: safe to re-run (`add column if not exists`, re-runnable
-- `comment on`).
--
-- HOW THIS IS APPLIED: by the migration runner,
-- `python -m flashml_cloud_api.migrate`, which records it in
-- public.schema_migrations. There are TWO databases, dev (auto-migrated on
-- merge to `develop`) and production (gated behind a manual workflow). Do not
-- apply it by hand to either — the runner is what keeps the two honest.
--
-- Ordering with the API: an API deployed BEFORE this migration lands would
-- select a column that does not exist and fail the whole provider read, so
-- this migration goes FIRST. That is the ordinary direction (additive schema,
-- then the code that reads it) and it is why the column is added rather than
-- the flag being computed.
--
-- Do not edit this file after it has been applied anywhere: the runner
-- checksums it, and an edit reads as drift and blocks every later migration.

alter table public.machines
    add column if not exists official boolean not null default false;

comment on column public.machines.official is
    'True for PLATFORM-OPERATED ANCHOR CAPACITY: a machine Zolli Labs runs '
    'itself, whose NAME IS PUBLIC. It is the one documented exception to the '
    'anonymisation rule in network._label — every other machine is shown to '
    'strangers as `prov…` plus six characters of its node id, because a '
    'machine name is routinely its owner''s own name. Setting this flag '
    'PUBLISHES machines.name to every signed-in viewer, so it is per-machine '
    'and explicit rather than inferred from who owns the row. It is NOT a '
    'quality score, a trust tier or a routing input: the trust tier is the '
    'three capability booleans (network._badge) and the router prices on '
    'measured acceptance (metrics.acceptance_rates). Default false; every '
    'machine enrolled before migration 0030 is false, which is the behaviour '
    'it already had.';
